dist: trusty
env:
  matrix:
    - CI_BUILD=cmake
    - CI_BUILD=autotools
language: cpp
os:
#  - osx
  - linux
compiler:
  - clang
  - gcc
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - clang-3.8
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - libcunit1-dev
    - libssl-dev
    - libev-dev
    - libcunit1-dev
    - cmake
    - cmake-data
before_install:
  - $CC --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" EXTRA_LDFLAGS="-fuse-ld=gold"; else export CXX="clang++-3.8" CC="clang-3.8"; fi; fi
  - $CC --version
  - cmake --version
before_script:
  # First build external lib
  - if [ ! -d ../openssl/build/lib ]; then ./ci/build_openssl.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libev; fi
  # configure ngtcp2
  - if [ "$CI_BUILD" == "autotools" ]; then autoreconf -i; fi
  - export PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig LDFLAGS="$EXTRA_LDFLAGS -Wl,-rpath,$PWD/openssl/build/lib"
  - if [ "$CI_BUILD" == "autotools" ]; then ./configure --enable-werror --enable-asan; fi
  # Set CMAKE_LIBRARY_ARCHITECTURE to workaround failure to parse implicit link information from GCC 5
  - if [ "$CI_BUILD" == "cmake" ]; then cmake -DENABLE_ASAN=1 -DCMAKE_LIBRARY_ARCHITECTURE=x86_64-linux-gnu; fi
script:
  # Now build ngtcp2 examples and test
  - make
  - make check
cache:
  directories:
  - ../openssl/build
